#!/bin/bash

while true; do
  PG_STATUS=`PGPASSWORD=$DATABASE_PASSWORD psql -U $DATABASE_USER  -w -h $DATABASE_HOST -c '\l \q' | grep postgres | wc -l`
  if ! [ "$PG_STATUS" -eq "0" ]; then
   break
  fi

  echo "Waiting Database Setup"
  sleep 10
done

if [[ "$DISCOURSE_ENABLED" == "True" ]]; then
  while true; do
    curl $DISCOURSE_UPSTREAM > /dev/null 2> /dev/null
    DISCOURSE_STATUS=$?

    if [[ "$DISCOURSE_STATUS" -eq "0" ]]; then
      break
    fi

    echo "Waiting Discourse Setup"
    sleep 10
  done
fi

DB_EXISTS=`PGPASSWORD=$DATABASE_PASSWORD psql -U $DATABASE_USER -w -h $DATABASE_HOST -tAc "SELECT 1 FROM pg_database WHERE datname='${DATABASE_NAME}'"`
if [[ "$DB_EXISTS" != "1" ]]; then
  PGPASSWORD=$DATABASE_PASSWORD psql -U $DATABASE_USER -w -h $DATABASE_HOST -c "CREATE DATABASE ${DATABASE_NAME} OWNER ${DATABASE_USER}"
fi

python3 src/manage.py migrate
python3 src/manage.py collectstatic --no-input
python3 src/manage.py ensure_initial_admin
python3 src/manage.py runserver 0.0.0.0:8000
